apiVersion: v1
kind: ReplicationController
metadata:
   name: hello-rc
spec:
   replicas: 5
   selector:
    app: hello-world
   template:
     metadata:
       labels:
          app: hello-world
     spec:
       containers:
       - name: hello-pod
         image: nginx:latest
         ports:
         - containerPort: 80
